language: swift
osx_image: xcode10
cache:
  directories:
    - Carthage
xcode_project: ReddiX.xcodeproj
xcode_scheme:
  - ReddiX
  - RAPI
  - UNI
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap --verbose --no-use-binaries --platform ios,watchos --cache-builds
